### PR TITLE
Refactoring old stuff

### PR DESCRIPTION
**Pull request by nomisum**
* move almost everything to cfgfunctions structure
* code optimizations
* bug fixes and enhancements
* better encapsulation of GUI stuff

todo:
* buy menu refactor (wont be done in the near future probably)

### CODE REVIEW

**Comment by nomisum** [comment]
there is a lot of potential for broken things, needs to be tested on dedicated

**Comment by AdlerSalbei** [comment]
Why does the file structur differ from grad standart with module in node_modules, functions in functions, pics/sounds/etc in data?

**Comment by nomisum** [comment]
2 reasons: PR is incomplete and more importantly mission specific things dont need to be modules, as they are not prone to reusage somewhere else

**Comment by AdlerSalbei** [comment]
I wasnt talking about the mssion specifics, these sould go into the functions folder. I was talking about the not mission specific modules.

**Comment by nomisum** [comment]
You are missing one important detail: node_modules is generated when building the mission.

Other than that (pic/data etc): Its just not a priority right now. It has grown this way for three years and more important things need to be done first, so that we come to a playable/stable state asap.

Biggest todo chunks are buymenu/faction implementation.

**Comment by AdlerSalbei** [comment]
Do you need any help?

**Comment by AdlerSalbei** [comment]
Ever thought about replacing the gear randomisation with the new grad-loadout feature?

**Comment by nomisum** [comment]
no

Salbei <notifications@github.com> schrieb am Do., 20. Dez. 2018, 19:11:

**Comment by AdlerSalbei** [comment]
No, you did not think about it or no you won't use it?

**Comment by nomisum** [comment]
You asked about thinking 😜

**Pull request merged**
