### PR TITLE
US VN adjustments & fix

### PR DESCRIPTION
**Pull request by Fusselwurm**
* give only low tech NVGs
* spawn CH-34 in appropriate height to not damage fuel tank
* ~~dont give GPS~~

### CODE REVIEW

**Review by nomisum — APPROVED** [review]
gps not necessary due to auto gps in air vehicles i suppose?

**Comment by Fusselwurm** [comment]
Uhm no. GPS not necessary because it doesn't fit the times. 

Is there a good argument why we should provide GPS even though we're playing 60s/70s technology?

**Comment by nomisum** [comment]
idk we shouldnt have BFT either if we follow down that path. would change difficulty quite a bit.

**Comment by Fusselwurm** [comment]
To re-iterate the status quo: 
* there is BFT 
* there are no GPS in loadout
* there is however *one* GPS per helicopter

It's hard to get any more inconsistent. 

Either we add GPS for everyone – thus being consistent with the magical BFT, 
or we remove it altogether – thus removing one inconsistency in the technological level (leaving BFT as magical device *for the map view only*

**Comment by nomisum** [comment]
there is one gps in each vehicle by default for the drivers. maybe i forgot to add them in VN 🤔

**Pull request merged**
